
--Q1. What is the total revenue generated by male vs. female customers?
 
 SELECT gender, SUM(purchase_amount) AS Revenue
 FROM customers
 group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount
from customers
where (discount_applied = 'Yes') AND purchase_amount > (select avg(purchase_amount) from customers)


-- Q3. Which are the top 5 products with the highest average review rating?

select top 5 item_purchased, round(avg(review_rating),2) as AverageReview 
from customers
group by item_purchased
order by AverageReview DESC

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 


select shipping_type, round(avg(purchase_amount),2) as AveragePurchase
from customers
where shipping_type in ('Express', 'Standard')
group by shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status, count(customer_id) as TotalSubscribers,
round(avg(purchase_amount),2) as AveragePurchase, 
sum(purchase_amount) as TotalPurchase,
from customers
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select top 5 item_purchased, 
round(100 * sum(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ COUNT(*) ,2) as Discount_Rate
from customers
group by item_purchased
order by Discount_Rate DESC


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

WITH CustomerType AS(
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END as CustomerSegment
from customers
)

select CustomerSegment, count(*) as TotalCustomers
from CustomerType
group by CustomerSegment

--Q8. What are the top 3 most purchased products within each category? 

with item_purchase as(
	select category, item_purchased, count(customer_id) as total_orders,
	ROW_NUMBER() OVER(partition by category order by count(customer_id) ) as itemRank
	from customers
	group by category, item_purchased
)
 
select itemRank,  category, item_purchased, total_orders from item_purchase
where itemRank <= 3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as totalsub
from customers
where previous_purchases > 5
group by subscription_status

- customer where count previous_purchase > 5 

--Q10. What is the revenue contribution of each age group? 

select age_group, sum(purchase_amount) as Revenue 
from customers
group by age_group
order by Revenue DESC

select * from [dbo].[customers]
